### ISSUE TITLE
Cannot install any magisk module from repo or third-party sources !

### ISSUE THREAD

**Issue by AlaeddineKJ** [topjohnwu/magisk-module-template#45]
Hi!
First of all I would like to thank you about this project because it makes rooting devices too much easier (especially MTK devices).
But after rooting I cannot install any magisk module from repo or third-party sources! I'm using the latest version of magisk (15.0) and the error is "this is not a magisk module" !!

**Comment by dark-1** [comment]
> Hi!
First of all I would like to thank you about this project because it makes rooting devices too much easier (especially MTK devices).
But after rooting I cannot install any magisk module from repo or third-party sources! I'm using the latest version of magisk (15.0) and the error is "this is not a magisk module" !!

Hi! @AlaeddineKJ ,
U r getting that error because Most module's are from v14.x and will take some time to migrate to v15.

**BUT** , Few can be installed from MagiskManager it self , without any such error's.

Best regards. 👍

**Comment by AlaeddineKJ** [comment]
Even "updated" modules are not working!! (such as "F-Droid Privileged Extension installer")

**Comment by sjayminsgithub** [comment]
You are getting "this is not a magisk module" !!!

The condition for a flashable zip to be a Magisk Module is that it contains "#MAGISK" in the updater-script, so, please check for that, if it is there, then try re-installing Magisk Manager

And also, do flashing from recovery work ??

**Comment by AlaeddineKJ** [comment]
It's working now (since few updates of Magisk 15)

**Comment by Didgeridoohan** [comment]
@AlaeddineKJ Care to close this?
